### ISSUE TITLE
Invalid session token

### ISSUE THREAD

**Issue by ardhityawiedhairawan** [amosayomide05/chatgpt-whatsapp-bot#1]
I found a problem.  I see the tokens change all the time. That's makes the token invalid everytime I run the node. How do you use tokens to make this work?

Thanks

**Comment by amosayomide05** [comment]
Yes, the token always change but that doesn't make it invalid

**Comment by amosayomide05** [comment]
You can try putting your token directly into the code

`const api = new ChatGPTAPI({
      sessionToken: "Your Token Here",
      markdown: false
    });`

**Comment by ardhityawiedhairawan** [comment]
> You can try putting your token directly into the code
> 
> `const api = new ChatGPTAPI({ sessionToken: "Your Token Here", markdown: false });`

I try this method, but I still get "invalid token". 

By the way, I run the puppeter with headless: true. What do you think?

**Comment by amosayomide05** [comment]
Try sharing a screenshot of your code

**Comment by amosayomide05** [comment]
Please create an issue here instead
https://github.com/transitive-bullshit/chatgpt-api


The error is not from the Whatsapp library 
But its still working for me

**Comment by ardhityawiedhairawan** [comment]
I agree with you. The WhatsApp library completely working. I think problem comes from chatgpt, im not sure and that's why I ask you.

Thank you for your assist. I still wondering how chatgpt working on your side. But I think its enough, lets close this issue. 🙂

**Comment by amosayomide05** [comment]
Yeah, but for now you can make use of GPT-3 openai till ChatGPT official api is released
